### ISSUE TITLE
Crash when loading fire gauntlet

### ISSUE THREAD

**Issue by PalgamingHD** [miyo6032/bosses-of-mass-destruction#4] opened 2021-04-16 04:20 UTC
This specific crash happened when opening the identity mod's menu, but pretty much any time trying summon/render the fire gauntlet entity this happens:

https://pastebin.com/DscFbQtF

**Comment by miyo6032** [comment] 2021-04-16 13:25
I am unable to replicate the crash doing either. Have you been able to get the crash to occur with only this mod and its dependencies?
- Are there any other mods installed? Can you get a list of those and versions? They may be listed on the crash report.
- Were you on a server, singleplayer, or LAN?

**Comment by PalgamingHD** [comment] 2021-04-17 02:34
Yeah I assumed its another mod, im on single player im going to debug it in a bit and i'll let you know what mod could be causing it, full mod list, ill first try optfine:

https://pastebin.com/CyZnSEVU

**Comment by miyo6032** [comment] 2021-04-17 13:37
Ok if you want to find out faster, take out about half of the mods (you have to watch out for dependencies still) and try to replicate the crash. If it crashes, you know it's in the first half of the mods, if it doesn't you know its in the second half that you took out. Either, way, you've eliminated half of the mods. You can repeat. Hopefully that makes sense!

**Comment by PalgamingHD** [comment] 2021-04-17 15:36
Yea i am doing exactly that, almost at the bottom of the list rn.

**Comment by PalgamingHD** [comment] 2021-04-17 17:47
ok, im left with these mods (still crashing), https://cdn.discordapp.com/attachments/789299328912326716/833035742904975440/unknown.png
They are all dependencies of BOMD and all up to date, uh...

**Comment by PalgamingHD** [comment] 2021-04-17 18:04
https://pastebin.com/vaEQMWUf

**Comment by miyo6032** [comment] 2021-04-17 22:26
I am unsure what the problem is. Give me some time to research and come up with a solution

**Comment by miyo6032** [comment] 2021-04-18 02:10
Ah, yes, I am dumb - the mod doesn't work for 1.16.4, only 1.16.5. I'll look further into why, but for now, the best solution to try is to update to 1.16.5 if you can.

**Comment by PalgamingHD** [comment] 2021-04-18 05:50
Alright, I'll see if I can until you are able to fix it, thanks

**Comment by miyo6032** [comment] 2021-04-23 14:09
Has been fixed in 1.0.2. The file is on github, will be uploading to curseforge later today

**Closed by miyo6032** 2021-04-23 14:09 UTC
